import pygame

keyAndValue = {pygame.K_BACKSPACE: 'backspace',
               pygame.K_TAB: 'tab',
               pygame.K_CLEAR: 'clear',
               pygame.K_RETURN: 'enter',
               pygame.K_PAUSE: 'pause',
               pygame.K_ESCAPE: 'esc',
               pygame.K_SPACE: 'space',
               pygame.K_EXCLAIM: 'exclaim',
               pygame.K_QUOTEDBL: 'quotable',
               pygame.K_HASH: 'hash',
               pygame.K_DOLLAR: 'dollar',
               pygame.K_AMPERSAND: '`',
               pygame.K_QUOTE: 'quote',
               pygame.K_LEFTPAREN: 'leftP',
               pygame.K_RIGHTPAREN: 'rightP',
               pygame.K_ASTERISK: 'asterisk',
               pygame.K_PLUS: 'plus',
               pygame.K_COMMA: 'comma',
               pygame.K_MINUS: 'minus',
               pygame.K_PERIOD: 'period',
               pygame.K_SLASH: '/',
               pygame.K_0: '0',
               pygame.K_1: '1',
               pygame.K_2: '2',
               pygame.K_3: '3',
               pygame.K_4: '4',
               pygame.K_5: '5',
               pygame.K_6: '6',
               pygame.K_7: '7',
               pygame.K_8: '8',
               pygame.K_9: '9',
               pygame.K_COLON: 'colon',
               pygame.K_SEMICOLON: 'semicolon',
               pygame.K_LESS: 'less-than',
               pygame.K_EQUALS: 'equals',
               pygame.K_GREATER: 'greater-than',
               pygame.K_QUESTION: 'question',
               pygame.K_AT: 'at',
               pygame.K_LEFTBRACKET: '[',
               pygame.K_BACKSLASH: '\\',
               pygame.K_RIGHTBRACKET: 'right bracket',
               pygame.K_CARET: 'caret',
               pygame.K_UNDERSCORE: 'underscore',
               pygame.K_BACKQUOTE: 'grave',
               pygame.K_a: 'a',
               pygame.K_b: 'b',
               pygame.K_c: 'c',
               pygame.K_d: 'd',
               pygame.K_e: 'e',
               pygame.K_f: 'f',
               pygame.K_g: 'g',
               pygame.K_h: 'h',
               pygame.K_i: 'i',
               pygame.K_j: 'j',
               pygame.K_k: 'k',
               pygame.K_l: 'l',
               pygame.K_m: 'm',
               pygame.K_n: 'n',
               pygame.K_o: 'o',
               pygame.K_p: 'p',
               pygame.K_q: 'q',
               pygame.K_r: 'r',
               pygame.K_s: 's',
               pygame.K_t: 't',
               pygame.K_u: 'u',
               pygame.K_v: 'v',
               pygame.K_w: 'w',
               pygame.K_x: 'x',
               pygame.K_y: 'y',
               pygame.K_z: 'z',
               pygame.K_DELETE: 'del',
               pygame.K_KP0: 'pad 0',
               pygame.K_KP1: 'pad 1',
               pygame.K_KP2: 'pad 2',
               pygame.K_KP3: 'pad 3',
               pygame.K_KP4: 'pad 4',
               pygame.K_KP5: 'pad 5',
               pygame.K_KP6: 'pad 6',
               pygame.K_KP7: 'pad 7',
               pygame.K_KP8: 'pad 8',
               pygame.K_KP9: 'pad 9',
               pygame.K_KP_PERIOD: 'pad period',
               pygame.K_KP_DIVIDE: 'pad divide',
               pygame.K_KP_MULTIPLY: 'pad mul',
               pygame.K_KP_MINUS: 'pad minus',
               pygame.K_KP_PLUS: 'pad plus',
               pygame.K_KP_ENTER: 'pad enter',
               pygame.K_KP_EQUALS: 'pad equals',
               pygame.K_UP: 'up',
               pygame.K_DOWN: 'down',
               pygame.K_RIGHT: 'right',
               pygame.K_LEFT: 'left',
               pygame.K_INSERT: 'inst',
               pygame.K_HOME: 'home',
               pygame.K_END: 'end',
               pygame.K_PAGEUP: 'pageUp',
               pygame.K_PAGEDOWN: 'pageDown',
               pygame.K_F1: 'F1',
               pygame.K_F2: 'F2',
               pygame.K_F3: 'F3',
               pygame.K_F4: 'F4',
               pygame.K_F5: 'F5',
               pygame.K_F6: 'F6',
               pygame.K_F7: 'F7',
               pygame.K_F8: 'F8',
               pygame.K_F9: 'F9',
               pygame.K_F10: 'F10',
               pygame.K_F11: 'F11',
               pygame.K_F12: 'F12',
               pygame.K_F13: 'F13',
               pygame.K_F14: 'F14',
               pygame.K_F15: 'F15',
               pygame.K_NUMLOCK: 'numLock',
               pygame.K_CAPSLOCK: 'capsLock',
               pygame.K_SCROLLOCK: 'scrollLock',
               pygame.K_RSHIFT: 'rShift',
               pygame.K_LSHIFT: 'lShift',
               pygame.K_RCTRL: 'rControl',
               pygame.K_LCTRL: 'lControl',
               pygame.K_RALT: 'rAlt',
               pygame.K_LALT: 'lAlt',
               pygame.K_RMETA: 'rMeta',
               pygame.K_LMETA: 'lMeta',
               pygame.K_LSUPER: 'lWin',
               pygame.K_RSUPER: 'rWin',
               pygame.K_MODE: 'shift',
               pygame.K_HELP: 'help',
               pygame.K_PRINT: 'printScreen',
               pygame.K_SYSREQ: 'sys',
               pygame.K_BREAK: 'break',
               pygame.K_MENU: 'menu',
               pygame.K_POWER: 'power',
               pygame.K_EURO: 'Euro',
               pygame.K_AC_BACK: 'Android back button',
               11: 'jUp.png',
               12: 'jDown.png',
               13: 'jLeft.png',
               14: 'jRight.png',
               0: 'jX.png',
               1: 'jO.png',
               2: 'jC.png',
               3: 'jT.png',
               7: 'jR.png',
               8: 'jL.png',
               9: 'jL1.png',
               10: 'jR1.png',
               5: 'Ps',
               15: '#',
               4: 'share',
               6: 'options',
               }
